<?xml version="1.0"?>
<package format="3">
  <name>k1_sim_isaac</name>
  <version>0.1.0</version>
  <description>Isaac Sim 6.0.1 launch and ROS2 bridge for Booster K1</description>
  <maintainer email="th.dhyan.us@gmail.com">thakk100</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>k1_interfaces</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
