[metadata]
name = k1_velocity
version = 0.1.0
description = RSL-RL velocity locomotion task for Booster K1
author = thakk100
author_email = th.dhyan.us@gmail.com
license = Apache-2.0

[options]
python_requires = >=3.10
install_requires =
    isaaclab

[options.packages.find]
where = source

[options.entry_points]
# Register Isaac Lab task
omni.isaac.lab.tasks =
    Isaac-Velocity-Rough-K1-v0 = k1_velocity.tasks.velocity:K1VelocityRoughEnvCfg
    Isaac-Velocity-Rough-K1-Play-v0 = k1_velocity.tasks.velocity:K1VelocityRoughPlayEnvCfg
